# Generated by Django 5.0 on 2023-12-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100, unique=True)),
                ('quiz_subject', models.CharField(max_length=100)),
                ('no_of_quiz', models.IntegerField()),
                ('quiz_type', models.CharField(max_length=100)),
                ('quiz_start_date', models.DateTimeField()),
                ('quiz_end_date', models.DateTimeField()),
                ('quiz_post_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_option', models.BooleanField()),
                ('text_option', models.TextField()),
                ('Question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizoSphere.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizoSphere.quiz'),
        ),
    ]
