# Generated by Django 5.0 on 2023-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoSphere', '0002_options_isanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='admin_name',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
