# Generated by Django 5.0 on 2023-12-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoSphere', '0003_quiz_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
